- name: This sets up an httpd webserver
  hosts: nginx
  become: yes
  remote_user: jenkins
  gather_facts: true
  tasks:
  - name: "Install httpd and php packages"
    package:
        name:
          - "httpd"
          - "php"
        state: present
  - name: "copy code from GitHub"
    get_url:
        url: https://www.shubhammishra.in
        dest: "/var/www/html/index.php"
  - name: "Start httpd services"
    service:
        name: httpd
        state: started
